=== Netcracker/qubership-envgene/schemas/paramset.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Parameter Set Object",
  "description": "Defines the Parameter Set which is container for a group of parameters",
  "additionalProperties": true,
  "properties": {
    "name": {
      "type": "string",
      "title": "Parameter Set Name",
      "description": "Name of the parameter set",
      "examples": [
        "paramset1"
      ]
    },
    "version": {
      "type": "number",
      "title": "Version Number",
      "description": "Version number of the specific parameter set",
      "examples": [
        1.2,
        2
      ]
    },
    "parameters": {
      "type": "object",
      "title": "Parameter Set Parameters",
      "description": "Parameters of the Parameter Set",
      "examples": [
        {
          "NAMESPACE": "main",
          "ESCAPE_SEQUENCE": "true"
        }
      ]
    },
    "applications": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "appName": {
            "type": "string",
            "title": "Application Name",
            "description": "Name of the application",
            "examples": [
              "app1",
              "app2"
            ]
          },
          "parameters": {
            "type": "object",
            "title": "Application Parameters",
            "description": "Application level parameters",
            "examples": [
              {
                "COMPOSITE_PLATFORM": "true"
              }
            ]
          }
        }
      },
      "required": [
        "appName",
        "parameters"
      ]
    }
  },
  "anyOf": [
    {
      "required": [
        "parameters"
      ]
    },
    {
      "required": [
        "applications"
      ]
    }
  ],
  "required": [
    "name"
  ]
}

=== Netcracker/qubership-envgene/samples/templates/parameters/composite-sample/data-management.json
{
    "name": "data-management",
    "version": 25.1,
    "parameters": {
        "PARAM_2": "value-2",
        "PARAM_6": "value-6"
    },
    "applications": [
        {
            "appName": "crm",
            "parameters": {
                "PARAM_1": "value-1",
                "PARAM_5": "value-5"
            }
        },
        {
            "appName": "cloud",
            "parameters": {
                "PARAM_3": "value-3",
                "PARAM_4": "value-4"
            }
        }
    ]
}

=== Netcracker/qubership-envgene/samples/environments/parameters/prod-shared.json
{
	"name": "prod-shared",
	"version": 25.1,
	"parameters": {},
	"applications": [
		{
			"appName": "NOTIFICATION",
			"parameters": {
				"NOTIFICATION_TOPIC": "customer.quote",
        		"NOTIFICATION_SERVICE_TOPIC" : "product.product",
        		"ORDER_NOTIFICATION_TOPIC" : "customer.order"
			}	
		}
	]
}

=== Netcracker/qubership-envgene/samples/environments/sample-cloud-name/composite-with-env-specific/Inventory/parameters/env-specific-bss.json
{
	"name": "env-specific-bss",
	"version": 23.1,
	"parameters": {
		"OVERRIDE_PARAMETER": "env-specific-value"
	},
	"applications": [
		{
			"appName": "NOTIFICATION",
			"parameters": {
				"NOTIFICATION_TOPIC": "customer.quote",
        		"NOTIFICATION_SERVICE_TOPIC" : "product.product",
        		"ORDER_NOTIFICATION_TOPIC" : "customer.order"
			}	
		}
	]
}
